### PR TITLE
setup typo

### PR DESCRIPTION
**Pull request by gmanchon**
the command to stop docker is described as start

### CODE REVIEW

**Comment by vtmoreau** [comment]
@gmanchon 
On Windows since we install the Docker Desktop App, we can't `sudo service docker start` from Ubuntu/WSL to start Docker.
Starting the Docker Desktop App on Windows does the job, afterwards docker commands in Ubuntu/WSL work fine.
image

**Comment by gmanchon** [comment]
@vtmoreau that's what I was thinking but I hoped to get away with a typo fix ;)

**Comment by gmanchon** [comment]
@vtmoreau can you add corresponding to the usage of the app ? 🥹 🙏

**Comment by gmanchon** [comment]
@vtmoreau updates are coming soon 👍

**Comment by gmanchon** [comment]
@vtmoreau ready for review 🙏

**Review by vtmoreau — COMMENTED** [review]
All Good 🙂

**Pull request merged**
