### PR TITLE
Data setup readme.es.md

### PR DESCRIPTION
**Pull request by lucasgday**

### CODE REVIEW

**Comment by ssaunier** [comment]
Amazing work @lucasgday, thank you very much!

@krokrob @gmanchon  do you know if the [build script](https://github.com/lewagon/data-setup/blob/data-setup-readme.es.md/build.rb) is able to generate translated versions of the setup? Where would that output the final `.md` ? Under an `es` subfolder?

**Comment by gmanchon** [comment]
is it ok to rename the partials without the `.es` according to the convention in the web repo for [fr](https://github.com/lewagon/setup/tree/master/_partials/fr) and [cn](https://github.com/lewagon/setup/tree/master/_partials/fr) ?

**Comment by gmanchon** [comment]
@lucasgday if you are still 🔥 for it, I added boilerplate english text for spanish sections in the main `README.md` page and the main `README.es.md` spanish page (diff visible in https://github.com/lewagon/data-setup/pull/191/commits/94c8f1267d3dec317da8c4151d7aaac35c8827e7)

**Comment by lucasgday** [comment]
Cool @gmanchon! @armandoteran could you translate the lines added in both READMEs?
Thanks!

**Comment by armandoteran** [comment]
On it @lucasgday

**Comment by krokrob** [comment]
Hello @ssaunier @lucasgday what process should we implement while updating the 🇬🇧 content?

**Comment by lucasgday** [comment]
Hey @krokrob, we have a #spanish-content Slack Channel on Alumni Workspace to share updates and translate them. Does it sound good?

> Hello @ssaunier @lucasgday what process should we implement while updating the 🇬🇧 content?

**Comment by lucasgday** [comment]
Hey @gmanchon @krokrob, what's missing to have [README.es.md](https://github.com/lewagon/data-setup/pull/191/files/7bbabde244ae7e4a5ad1f8712be248b14fbba225..0878baf078429244521ac0f7e733b4b5d2eca90d#diff-42010a55cd1784b825a37c762cc91d75421f3ed4515f1047cf5506444949a0c2) available?

Also, let me know if you'll edit [data-setup README.md](https://github.com/lewagon/data-setup/blob/master/README.md) to be similar to [web-setup README.md](https://github.com/lewagon/setup/blob/setup-readme.es.md/README.md) or you want me to do it!

Thanks!

**Comment by gmanchon** [comment]
Hello @lucasgday, I added a link from the main readme to the spanish one but my spanish is basically inexistant, would you translate the header and text ?

**Comment by lucasgday** [comment]
@gmanchon ✅

**Comment by lucasgday** [comment]
Anything else missing @gmanchon ?

**Comment by gmanchon** [comment]
Looks good to me... @ssaunier @krokrob WDYT ?

**Comment by lucasgday** [comment]
Hi! Please ping me if there's anything missing on my side to enable this merge @ssaunier @krokrob @gmanchon !
Thanks!

**Pull request merged**
