### PR TITLE
add gha to build guides

### LINKED ISSUE #15: GitHub action to run `ruby build.rb`
that would be great

### PR DESCRIPTION
**Pull request by krokrob**
this fixes #15 @ssaunier please review

### CODE REVIEW

**Comment by ssaunier** [comment]
I'm not sure this is properly working as the `build.rb` assumes that both `lewagon/setup` and `lewagon/data-setup` are cloned on the machine running the script 🤔

**Comment by krokrob** [comment]
You're right, I was so happy to see the build pass, I forgot that part. Let me check

**Comment by krokrob** [comment]
the generated files are OK

**Comment by ssaunier** [comment]
OK let's give it a go then.

**Comment by ssaunier** [comment]
🔴 🙈 https://github.com/lewagon/data-setup/runs/1630751032?check_suite_focus=true

**Comment by krokrob** [comment]
I don't understand why the action is triggered on the `merge` because it is set to be triggered on the `push`

**Comment by ssaunier** [comment]
I don't think `push` means that in the context of a GitHub Actions. From my understanding it means "run on every new `commit` in the `master` branch". Can you confirm @progapandist ?

**Comment by krokrob** [comment]
I need to ignore `master` https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-ignoring-branches-and-tags

**Comment by ssaunier** [comment]
Well, I don't think so, you want to run this script in `master`. The script needs to be smarter and not fail if there's nothing to commit/push if the guides have already been generated and are up to date.

**Comment by progapandist** [comment]
Push just means the new commit indeed

**Pull request merged**
