### PR TITLE
add htop ncdu and tig for macOSX & ubuntu

### PR DESCRIPTION
**Pull request by krokrob**
@ssaunier this adds useful tools for terminal. 

@barangerbenjamin can you investigate for a Windows Git Bash alternative to `htop` and `ncdu` please? For `htop` I found `handle` edited by Microsoft. https://docs.microsoft.com/en-us/sysinternals/downloads/handle

### CODE REVIEW

**Comment by barangerbenjamin** [comment]
Just tested `handle`. Works fine
Click on `Download Handle`
Extract the archive.
Copy `handle.exe` in `C:\WINDOWS\System32`
Restart Git Bash.
Run with the command `handle`

Will look for a `ncdu` equivalent

**Comment by barangerbenjamin** [comment]
What about `windirstat` ? 
It has a GUI, not pretty but I've been using it for as long as I can remember.

https://windirstat.net/

**Comment by krokrob** [comment]
thanks a lot @barangerbenjamin ! OK we will go with windirstat for windows users

**Comment by krokrob** [comment]
@ssaunier @barangerbenjamin this adds Handle and WinDirStat for Windows. Ready for final review

**Comment by ssaunier** [comment]
Not sure about the usefulness of `tig`, but merging anyway.

**Pull request merged**
