### PR TITLE
setup Q4 2022

### PR DESCRIPTION
**Pull request by gmanchon**
- **python 3.10.6**
- **tensorflow 2.10.0** (or tensorflow-macos)
- **remove rosetta** use for apple silicon setup

requirements files generated from https://github.com/lewagon/utils/pull/81

windows : restore use of the `BROWSER` environment variable through the web `setup/windows_browser` partial. This is required by ubuntu 22.04 in order to allow the ubuntu cli to open the windows browser cc @vtmoreau

### CODE REVIEW

**Review by vtmoreau — APPROVED** [review]
LGTM, awesome to use Python 3.10 🙂 
Did the whole Setup on Win10 this morning, python things go smoothly.

Did not review the `past/` folders
Spanish instructions seem fine, but maybe we should ping someone from the LATAM team to make sure
Also this file: `_sublime_text.md`, I don't know what it is used for 🙈

**Comment by gmanchon** [comment]
Thanks @vtmoreau, `_sublime_text.md ` just contains a find in files filter to ease the job ;)

**Comment by gmanchon** [comment]
@lucasgday can you have a look at the spanish version please ? 🙏

**Comment by lucasgday** [comment]
Hi @gmanchon , I committed and created 3 PRs to update the three mentioned partials.
Let me know if there's anything else I should review!
Thanks!

**Pull request merged**
