### PR TITLE
[vscode] use flake8 as default linter

### PR DESCRIPTION
**Pull request by gmanchon**
use flake8 instead of pylint

syntax issues are highlighted whenever the file is saved

### CODE REVIEW

**Comment by brunolajoie** [comment]
Il manque aussi je crois
```
"python.linting.enabled": true,
```

**Comment by gmanchon** [comment]
@brunolajoie I added the linting enabler pref 👍

**Comment by brunolajoie** [comment]
Thinking it through, don't need any additional linter at all, because Pylance is already linting out code!

This
image
gives you
image


While this
image
gives you a DOUBLE LINTING
image

**Comment by gmanchon** [comment]
@brunolajoie pylance seems to care about parenthesis :

Screenshot 2021-04-15 at 09 56 05

But not about spaces :

Screenshot 2021-04-15 at 09 56 05

While flake8 seems to cares about both :

Screenshot 2021-04-15 at 09 58 12

**Comment by gmanchon** [comment]
flake8 also seems to support unused variables and go to definitions, I'll check the diffs between VSCode linters / formatter and language server 👍

**Comment by gmanchon** [comment]
flake8 supports unused variables and go to def, but not autocompletion 👍

**Comment by brunolajoie** [comment]
Nor Autodocstring I guess. Pretty important in DataScience.

It's probably better to stick to Pylance in that case. The linter is already good: it just shows you important errors

Then, when we want to enforce PeP8 format, we just Command-Palette-->Autoformat

**Pull request closed without merging**
